-- 코드를 입력하세요
SELECT t1.TITLE,t1.BOARD_ID,t2.REPLY_ID,t2.WRITER_ID,t2.CONTENTS,DATE_FORMAT(t2.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE FROM USED_GOODS_BOARD as t1
JOIN USED_GOODS_REPLY as t2 ON t1.board_id = t2.board_id
WHERE t1.CREATED_DATE LIKE "2022-10%"
ORDER BY CREATED_DATE ASC, TITLE ASC

